is_adjacent(washington,idaho).
is_adjacent(washington,oregon).
is_adjacent(oregon,washington).
is_adjacent(oregon,idaho).
is_adjacent(oregon,nevada).
is_adjacent(oregon,california).
is_adjacent(california,oregon).
is_adjacent(california,nevada).
is_adjacent(california,arizona).
is_adjacent(nevada,california).
is_adjacent(nevada,oregon).
is_adjacent(nevada,idaho).
is_adjacent(nevada,utah).
is_adjacent(nevada,arizona).
is_adjacent(idaho,oregon).
is_adjacent(idaho,washington).
is_adjacent(idaho,montana).
is_adjacent(idaho,wyoming).
is_adjacent(idaho,utah).
is_adjacent(idaho,nevada).
is_adjacent(utah,nevada).
is_adjacent(utah,idaho).
is_adjacent(utah,wyoming).
is_adjacent(utah,colorado).
is_adjacent(utah,arizona).
is_adjacent(arizona,california).
is_adjacent(arizona,nevada).
is_adjacent(arizona,utah).
is_adjacent(arizona,newmexico).
is_adjacent(montana,idaho).
is_adjacent(montana,northdakota).
is_adjacent(montana,southdakota).
is_adjacent(montana,nebraska).
is_adjacent(montana,wyoming).
is_adjacent(wyoming,idaho).
is_adjacent(wyoming,montana).
is_adjacent(wyoming,southdakota).
is_adjacent(wyoming,nebraska).
is_adjacent(wyoming,colorado).
is_adjacent(wyoming,utah).
is_adjacent(colorado,utah).
is_adjacent(colorado,wyoming).
is_adjacent(colorado,nebraska).
is_adjacent(colorado,kansas).
is_adjacent(colorado,oklahoma).
is_adjacent(colorado,newmexico).
is_adjacent(newmexico,arizona).
is_adjacent(newmexico,utah).
is_adjacent(newmexico,colorado).
is_adjacent(newmexico,oklahoma).
is_adjacent(newmexico,texas).
is_adjacent(northdakota,montana).
is_adjacent(northdakota,minnesota).
is_adjacent(northdakota,southdakota).
is_adjacent(southdakota,wyoming).
is_adjacent(southdakota,montana).
is_adjacent(southdakota,northdakota).
is_adjacent(southdakota,minnesota).
is_adjacent(southdakota,iowa).
is_adjacent(southdakota,nebraska).
is_adjacent(nebraska,wyoming).
is_adjacent(nebraska,southdakota).
is_adjacent(nebraska,iowa).
is_adjacent(nebraska,missouri).
is_adjacent(nebraska,kansas).
is_adjacent(nebraska,colorado).
is_adjacent(kansas,colorado).
is_adjacent(kansas,nebraska).
is_adjacent(kansas,missouri).
is_adjacent(kansas,oklahoma).
is_adjacent(oklahoma,newmexico).
is_adjacent(oklahoma,colorado).
is_adjacent(oklahoma,kansas).
is_adjacent(oklahoma,missouri).
is_adjacent(oklahoma,arkansas).
is_adjacent(oklahoma,texas).
is_adjacent(texas,newmexico).
is_adjacent(texas,oklahoma).
is_adjacent(texas,arkansas).
is_adjacent(texas,louisiana).
is_adjacent(minnesota,northdakota).
is_adjacent(minnesota,southdakota).
is_adjacent(minnesota,iowa).
is_adjacent(minnesota,wisconsin).
is_adjacent(iowa,nebraska).
is_adjacent(iowa,southdakota).
is_adjacent(iowa,minnesota).
is_adjacent(iowa,wisconsin).
is_adjacent(iowa,illinois).
is_adjacent(iowa,missouri).
is_adjacent(missouri,kansas).
is_adjacent(missouri,nebraska).
is_adjacent(missouri,iowa).
is_adjacent(missouri,illinois).
is_adjacent(missouri,kentucky).
is_adjacent(missouri,tennessee).
is_adjacent(missouri,arkansas).
is_adjacent(missouri,oklahoma).
is_adjacent(arkansas,oklahoma).
is_adjacent(arkansas,missouri).
is_adjacent(arkansas,tennessee).
is_adjacent(arkansas,mississippi).
is_adjacent(arkansas,louisiana).
is_adjacent(wisconsin,minnesota).
is_adjacent(wisconsin,illinois).
is_adjacent(wisconsin,iowa).
is_adjacent(illinois,iowa).
is_adjacent(illinois,wisconsin).
is_adjacent(illinois,indiana).
is_adjacent(illinois,kentucky).
is_adjacent(illinois,missouri).
is_adjacent(michigan,indiana).
is_adjacent(michigan,ohio).
is_adjacent(indiana,illinois).
is_adjacent(indiana,michigan).
is_adjacent(indiana,ohio).
is_adjacent(indiana,kentucky).
is_adjacent(kentucky,missouri).
is_adjacent(kentucky,illinois).
is_adjacent(kentucky,indiana).
is_adjacent(kentucky,ohio).
is_adjacent(kentucky,westvirginia).
is_adjacent(kentucky,virginia).
is_adjacent(kentucky,tennessee).
is_adjacent(tennessee,arkansas).
is_adjacent(tennessee,missouri).
is_adjacent(tennessee,kentucky).
is_adjacent(tennessee,virginia).
is_adjacent(tennessee,northcarolina).
is_adjacent(tennessee,georgia).
is_adjacent(tennessee,alabama).
is_adjacent(tennessee,mississippi).
is_adjacent(mississippi,louisiana).
is_adjacent(mississippi,arkansas).
is_adjacent(mississippi,tennessee).
is_adjacent(mississippi,alabama).
is_adjacent(louisiana,texas).
is_adjacent(louisiana,arkansas).
is_adjacent(louisiana,mississippi).
is_adjacent(alabama,mississippi).
is_adjacent(alabama,tennessee).
is_adjacent(alabama,georgia).
is_adjacent(alabama,florida).
is_adjacent(florida,alabama).
is_adjacent(florida,georgia).
is_adjacent(georgia,alabama).
is_adjacent(georgia,tennessee).
is_adjacent(georgia,northcarolina).
is_adjacent(georgia,southcarolina).
is_adjacent(georgia,florida).
is_adjacent(ohio,indiana).
is_adjacent(ohio,michigan).
is_adjacent(ohio,pennsylvania).
is_adjacent(ohio,westvirginia).
is_adjacent(ohio,kentucky).
is_adjacent(southcarolina,northcarolina).
is_adjacent(southcarolina,georgia).
is_adjacent(northcarolina,tennessee).
is_adjacent(northcarolina,virginia).
is_adjacent(northcarolina,southcarolina).
is_adjacent(northcarolina,georgia).
is_adjacent(virginia,kentucky).
is_adjacent(virginia,westvirginia).
is_adjacent(virginia,maryland).
is_adjacent(virginia,northcarolina).
is_adjacent(virginia,tennessee).
is_adjacent(westvirginia,kentucky).
is_adjacent(westvirginia,ohio).
is_adjacent(westvirginia,pennsylvania).
is_adjacent(westvirginia,maryland).
is_adjacent(westvirginia,virginia).
is_adjacent(pennsylvania,ohio).
is_adjacent(pennsylvania,newyork).
is_adjacent(pennsylvania,newjersey).
is_adjacent(pennsylvania,delaware).
is_adjacent(pennsylvania,maryland).
is_adjacent(pennsylvania,westvirginia).
is_adjacent(maryland,westvirginia).
is_adjacent(maryland,pennsylvania).
is_adjacent(maryland,delaware).
is_adjacent(maryland,virginia).
is_adjacent(delaware,pennsylvania).
is_adjacent(delaware,maryland).
is_adjacent(delaware,newjersey).
is_adjacent(newjersey,pennsylvania).
is_adjacent(newjersey,newyork).
is_adjacent(newjersey,delaware).
is_adjacent(newyork,pennsylvania).
is_adjacent(newyork,vermont).
is_adjacent(newyork,massachusetts).
is_adjacent(newyork,connecticut).
is_adjacent(newyork,newjersey).
is_adjacent(connecticut,newyork).
is_adjacent(connecticut,massachusetts).
is_adjacent(connecticut,rhodeisland).
is_adjacent(massachusetts,newyork).
is_adjacent(massachusetts,vermont).
is_adjacent(massachusetts,newhampshire).
is_adjacent(massachusetts,rhodeisland).
is_adjacent(massachusetts,connecticut).
is_adjacent(rhodeisland,connecticut).
is_adjacent(rhodeisland,massachusetts).
is_adjacent(vermont,newyork).
is_adjacent(vermont,newhampshire).
is_adjacent(vermont,massachusetts).
is_adjacent(newhampshire,vermont).
is_adjacent(newhampshire,maine).
is_adjacent(newhampshire,massachusetts).
is_adjacent(maine,newhampshire).
