is_adjacent(washington,idaho).
is_adjacent(washington,oregon).
is_adjacent(oregon,washington).
is_adjacent(oregon,idaho).
is_adjacent(oregon,nevada).
is_adjacent(oregon,california).
is_adjacent(california,oregon).
is_adjacent(california,nevada).
is_adjacent(california,arizona).
is_adjacent(nevada,california).
is_adjacent(nevada,oregon).
is_adjacent(nevada,idaho).
is_adjacent(nevada,utah).
is_adjacent(nevada,arizona).
is_adjacent(idaho,oregon).
is_adjacent(idaho,washington).
is_adjacent(idaho,montana).
is_adjacent(idaho,wyoming).
is_adjacent(idaho,utah).
is_adjacent(idaho,nevada).
is_adjacent(utah,nevada).
is_adjacent(utah,idaho).
is_adjacent(utah,wyoming).
is_adjacent(utah,colorado).
is_adjacent(utah,arizona).
is_adjacent(arizona,california).
is_adjacent(arizona,nevada).
is_adjacent(arizona,utah).
is_adjacent(arizona,newmexico).
is_adjacent(montana,idaho).
is_adjacent(montana,northdakota).
is_adjacent(montana,southdakota).
is_adjacent(montana,nebraska).
is_adjacent(montana,wyoming).
is_adjacent(wyoming,idaho).
is_adjacent(wyoming,montana).
is_adjacent(wyoming,southdakota).
is_adjacent(wyoming,nebraska).
is_adjacent(wyoming,colorado).
is_adjacent(wyoming,utah).
is_adjacent(colorado,utah).
is_adjacent(colorado,wyoming).
is_adjacent(colorado,nebraska).
is_adjacent(colorado,kansas).
is_adjacent(colorado,oklahoma).
is_adjacent(colorado,newmexico).
is_adjacent(newmexico,arizona).
is_adjacent(newmexico,utah).
is_adjacent(newmexico,colorado).
is_adjacent(newmexico,oklahoma).
is_adjacent(newmexico,texas).
is_adjacent(northdakota,montana).
is_adjacent(northdakota,minnesota).
is_adjacent(northdakota,southdakota).
is_adjacent(southdakota,wyoming).
is_adjacent(southdakota,montana).
is_adjacent(southdakota,northdakota).
is_adjacent(southdakota,minnesota).
is_adjacent(southdakota,iowa).
is_adjacent(southdakota,nebraska).
is_adjacent(nebraska,wyoming).
is_adjacent(nebraska,southdakota).
is_adjacent(nebraska,iowa).
is_adjacent(nebraska,missouri).
is_adjacent(nebraska,kansas).
is_adjacent(nebraska,colorado).
is_adjacent(kansas,colorado).
is_adjacent(kansas,nebraska).
is_adjacent(kansas,missouri).
is_adjacent(kansas,oklahoma).
is_adjacent(oklahoma,newmexico).
is_adjacent(oklahoma,colorado).
is_adjacent(oklahoma,kansas).
is_adjacent(oklahoma,missouri).
is_adjacent(oklahoma,arkansas).
is_adjacent(oklahoma,texas).
is_adjacent(texas,newmexico).
is_adjacent(texas,oklahoma).
is_adjacent(texas,arkansas).
is_adjacent(texas,louisiana).
